# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9803ffeaeea9d07b94b90f85bbbfdbfb8fc2353147bc04838516d75be4907b7817d40dfe094af94a9881d581a44ac5d67ee6e2bd1825678031fc0f816863fbe7

test:
  secret_key_base: 34e5743742d4a23b18aaa2a46f8f3cdaddd5ce6d61f6cbbeb10b09eb0a86a16823f1336a85900037e38b006757361db683e9506226b7db6d9bdc3084ee7fd8ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
